# Generated by Django 3.2 on 2022-06-18 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('link', models.URLField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TechnologyITArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('it_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='summary.itarea')),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='summary.technology')),
            ],
        ),
        migrations.AddField(
            model_name='itarea',
            name='technologies',
            field=models.ManyToManyField(related_name='it_areas', through='summary.TechnologyITArea', to='summary.Technology'),
        ),
    ]
