###
POST http://127.0.0.1:8000/api/v1/skills_list/
Content-Type: application/json
Authorization: Token ===== only superuser token =====


{
    "name": "Apache server",
    "slug": "apache_server",
    "description": "The Apache HTTP Server Project is an effort to develop and maintain an open-source HTTP server for modern operating systems including UNIX and Windows. The goal of this project is to provide a secure, efficient and extensible server that provides HTTP services in sync with the current HTTP standards.",
    "is_published": false,
    "it_area": 1,
    "work": 1
  }