# Generated by Django 3.2 on 2022-06-18 04:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'it area',
                'verbose_name_plural': 'it areas',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', embed_video.fields.EmbedVideoField()),
            ],
            options={
                'verbose_name': 'video',
                'verbose_name_plural': 'videos',
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=2000)),
                ('about_experience', models.TextField(blank=True, max_length=2000)),
                ('position', models.CharField(max_length=255)),
                ('logo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('start', models.DateField(verbose_name='time of start working')),
                ('end', models.DateField(blank=True, null=True, verbose_name='time of end working')),
                ('site', models.URLField(verbose_name='work url address')),
            ],
            options={
                'verbose_name': 'work',
                'verbose_name_plural': 'works',
                'ordering': ['-start', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('logo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True)),
                ('it_area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.itarea')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suggested_skills', to=settings.AUTH_USER_MODEL)),
                ('work', models.ForeignKey(default=2, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='skills', to='core.work')),
            ],
            options={
                'verbose_name': 'skill',
                'verbose_name_plural': 'skills',
                'ordering': ['time_create', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Job', 'Job'), ('Contribution', 'Contribution'), ('Other', 'Other')], default='Job', max_length=255)),
                ('content', models.TextField()),
                ('age_confirmation', models.BooleanField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='feedback_images/%Y/%m/%d/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
